### ISSUE TITLE
Overall Task Tracking

### ISSUE THREAD

**Issue by JanghyunJK** [NREL/edv_synthetic_smart_meter_data#131]
---
**MERGING EXISTING BRANCHES**

- [x] ```BSync_Generation_with_DailyTimeseries``` (by 10/16/2020)
: delete this branch - JK

- [x] ```typical-operation-hour algorithm``` (by 10/16/2020)
: this branch includes all work related to typical hours milestone - JK
: including python script for quantifying start/stop time detection - JK
: including rake task - JK
: merge this branch to ```develop``` - JK
: set Lin as reviewer, and Lin to review before merging

- [x] ```BDGP2_implementation``` (by 10/16/2020)
: pull ```BDGP2_bugfix``` from ```BDGP2_implementation``` - LA
: delete ```BDGP2_implementation``` - LA

- [ ] ```BDGP2_bugfix``` (by 11/6/2020)
: review changes in ```BDGP2_bugfix``` branch and merge to ```develop``` - LA: PR #132 in progress.
: #135 bugfix testing (by 11/6/2020).

- [ ] solve issue around openstudio simulation process (start from 11/13/2020)
: currently, simulations are not done properly
: and not generating simulated outputs
: review what's going on - LA
: seek help if necessary

- [ ] sf_monthly_merge
: check ```sf_monthly_setback``` and ```sf_monthly``` - LA
: merge above two to ```sf_monthly_merge``` - LA
: ```sf_monthly_merge``` to be the last merge to the workflow? - LA

---
**CLEANING**

- [ ] refactoring directory - LA - (OCT 2020 to MAR 2021)
: revisiting paths/directories for inputs/outputs used in scripts

- [ ] review scripts that are used often - LA - (OCT 2020 to MAR 2021)
: revisit existing codes 
: document issues

- [ ] delete unused scripts - LA - (OCT 2020 to MAR 2021)
: revisit each script (each *rb file)
: see if the script is being used in the current workflow
: understand why it was created before
: make decision on deleting

- [ ] found this [chunk](https://github.com/NREL/edv-experiment-1/blob/69a4b9621cafb13cd5722f387f4900084f49de12/scripts/meta_to_buildingsync.rb#L915) under if statement is doing nothing - LA - (OCT 2020 to MAR2021)
: compatible with current BSync schema?
: need to be included or not?
: need fix or not?

- [ ] revisiting metadata labels used for BDGP workflow - LA - (OCT 2020 to MAR 2021)
: related to the previous item, some of these labels are not used in BSync conversion
: what are the ones that are necessary?
: what are the ones that are not necessary?
: do we need any other label types?

---
**CORRECTING**

- [x] correct math calculation - LA - (AUG to SEP 2020)
: all issues found from reviewing SF data incorporation
: branch off of ```BDGP2_implementation```
: focus only on correcting measured data calculation etc.

- [ ] correct openstudio simulation fails - LA - (early FY21)
: add description

- [ ] correct multi-year measurements storing in BSync - LA - (OCT 2020 to MAR2021)
: BDGP data can have measurements in multiple years
: current BSync only takes one annual value
: might need to have ways to save multiple years of annual total values.

- [ ] standardizing building types - JK - (OCT 2020 to MAR2021)
: when BSync xml is converted to osm, a certain prototype building model is selected based on occupancy type in BSync
: since building type can be defined in various ways, a new data source will have problem in terms of selecting the right building type
: so do we want to standardize building types up front? giving users a lookup for typical building type classification versus prototype building models?

---
**UPDATING/IMPROVING**

- [x] include functionality for using BDGP2 data as direct input - JK - (AUG to SEP 2020)
: review/modify meta_to_buildingsync.rb to include all metadata from BDGP2 to BSync XML

- [x] Adding capabilities for handling granular timeseries data: hourly - LA - (AUG to SEP 2020)
: current workflow only handles monthly data
: workflow should also handle hourly data
: hourly feature necessary for testing typical hours of operation algorithm

- [x] implement algorithm for estimating typical operating hours of buildings - JK - (AUG to SEP 2020)
: review Liang's code (python including python libraries)
: check code-based "requirement.txt" and see if the entire thing is compiled/packaged
: use BDGP2 data set, convert BSync files, calculate typical hours of operation (distribution) for 1500 buildings
: base off of develop branch and make necessary changes for intaking BDGP2
: finish both BDGP2 and Liang's code implementations within August

- [ ] update standard timeseries file format - JK - (OCT 2020 to MAR 2021)
: add "FuelType" column right after timestamp column
: to have capability for intaking timeseries interval data for multiple fuel types (e.g., elec, natural gas, chilled water, steam etc.)

- [ ] update code based on BSync 2.1 - LA - (OCT 2020 to MAR 2021)
: review script
: cover all elements that are included in BSync 2.1
: but follow NMEC proposal for NMEC specific elements 

- [ ] include functionality for using SF data as direct input - LA - (OCT 2020 to MAR 2021)
: review/merge SF_monthly branch to develop

- [ ] update gems and make necessary changes - LA - (OCT 2020 to MAR 2021)
: if gems in gemfile are all used with their latest versions, will the synthetic-data-creation workflow fail?
: if yes, what needs to be fixed?
: check gems being used in EDV (especially the gemfile)
: compare with the latest version of each gem
: test compatibility with EDV workflow
: make necessary changes.
: remain with current gem versions until the end of FY20
: revisit gem versions in the beginning of FY21 = 10/1/2020

- [ ] update readme/wiki - JK - (OCT 2020 to MAR 2021)
: include necessary contents into both readme and wiki, monthly/bi-monthly.
: in readme, how to install, how to execute command, what commands are available etc.
: in wiki, what is the background information, what kind of features are included etc.
: refer to [this](https://github.com/NREL/edv-experiment-1/issues/130) ticket

- [ ] Creating unit tests for existing code base - LA - (OCT 2020 to MAR 2021)
: create/review test scripts. to have comprehensive suite of unit tests

- [ ] review energy efficiency measures (EEM) implementation - JK - (OCT 2020 to MAR 2021)
: there are two ways of EEM implemenation in the current workflow,
: via predefined EEM information in BuildingSync xmls. Use case: information (retrofit type, event date) being added from the data owner.
: via variability gem using non-routine event measures. Use case: if user is willing to estimate the impact of new EEMs which is not included in the original BSync file.
: need both approaches?

- [ ] specify open source license type before going public - JK - (OCT 2020 to MAR 2021)
: probably BSD3

- [ ] Implement Jenkins CI - LA - (OCT 2020 to MAR 2021)
: include description

- [ ] Workflow upgrade to have compatibility against OS 3.0 and Ruby 2.5.5 - LA - (OCT 2020 to MAR 2021)
: include description

- [ ] improve workflow connecting with NMEC - LA - (OCT 2020 to MAR 2021)
: creating a script for storing NMEC results back to BSync
: including capability for including not only monthly but also daily and hourly methods
---
