### ISSUE TITLE
[Task: algorithm] typical hours of operation understanding/planning

### ISSUE THREAD

**Issue by JanghyunJK** [NREL/edv_synthetic_smart_meter_data#90]
**Milestone description**
Develop an algorithm to estimate typical hours of operation for a site from hourly energy use timeseries data. Demonstrate ability to use estimated hours of operation in the BuildingSync gem based EDV Experiment 1 workflow.

- [x] see if adopting the process from [this study](https://linkinghub.elsevier.com/retrieve/pii/S030626192030982X) is doable
  - applying filter to AMI data
  - apply Price's method for dis-aggregating load profile characteristics
  - understand the distribution of operating hours of buildings
  - find appropriate typical operating hours that represents each building
- [ ] modify workflow to intake BDGP2 
  - mismatch in metadata compared to BDGP1
  - hourly timeseries data should be included in the resultant BSync xml
- [ ] reivew adopted method
  - timeseries reformatting
  - SG filter implementation
  - profile characterization
- [ ] implement adopted method
- [ ] apply/test method on entire BDGP data set
  - use workflow to create BSync from BDGP2 (including hourly timeseries data)
  - read timeseries from BSync for each building
  - apply algorithm to calculate typical hours of operation (start time, duration) metric
    - mean, median, std dev
    - histogram for each day of week
- [ ] revise algorithm
